### ISSUE TITLE
Consider user's vehicle params when searching for stations

### ISSUE THREAD

**Issue by lizyn** [AdvisorChuanChuan/CIS550-JuiceFinder#35]
Currently it's ignored and no filters are applied

**Comment by lizyn** [comment]
Read configurations from user settings

**Comment by lizyn** [comment]
user settings is in databse, useid is in context (currentUser.id)

**Comment by AdvisorChuanChuan** [comment]
![Image](https://user-images.githubusercontent.com/56421810/235281768-05b4ce98-a0f3-4ba8-8c1a-69a2f7243a3c.png)
