### ISSUE TITLE
SQL Query in GET /restaurants/nearby/:longitude/:latitude

### ISSUE THREAD

**Issue by YichengShen** [AdvisorChuanChuan/CIS550-JuiceFinder#69]
I think the current returned results are a little bit weird.

```
periodQuery = `
      AND TIME('${startTime}') >= TIME(SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(hours, CONCAT('$."', '${day}', '"'))), '-', 1))
      AND TIME('${endTime}') <= TIME(SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(hours, CONCAT('$."', '${day}', '"'))), '-', -1))
    `;
```

In the code above, `startTime` is the starting point on the slider, and `endTime` is the endpoint on the slider.

My understanding is that our expected returned results are restaurants that are open between `startTime` and `endTime`. 

In this case, imagine a line segment with two endpoints, the `startTime` and `endTime`, and imagine another line segment with endpoints being a restaurant's open time and close time. This restaurant is returned if the restaurant line segment is contained in our input line segment.

So, I think the first line of the query should use `<=` and the second line should use `>=`.

@AdvisorChuanChuan Please check whether my understanding is correct.

**Comment by AdvisorChuanChuan** [comment]
Change 'open time' to 'visiting time'
